# Generated by Django 5.1 on 2024-08-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NaverFinance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strd_dt", models.CharField(help_text="기준일자", max_length=8)),
                ("stock_cd", models.CharField(help_text="종목코드", max_length=10)),
                ("stock_nm", models.CharField(help_text="종목명", max_length=500)),
                ("pre_price", models.CharField(help_text="전일가", max_length=500)),
                ("today_price", models.CharField(help_text="현재가", max_length=500)),
                ("trading_volume", models.CharField(help_text="거래량", max_length=500)),
                ("ins_dt", models.CharField(help_text="입력일시", max_length=500)),
            ],
            options={
                "db_table": "dbms_naver_finance",
            },
        ),
    ]
