# Generated by Django 5.1 on 2024-08-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvCarPortal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strd_dt", models.CharField(help_text="기준일자", max_length=8)),
                ("sido_nm", models.CharField(help_text="시도명", max_length=500)),
                ("region", models.CharField(help_text="지역명", max_length=500)),
                ("receipt_way", models.CharField(help_text="접수방법", max_length=500)),
                (
                    "receipt_priority",
                    models.CharField(help_text="접수순위", max_length=500),
                ),
                ("value", models.CharField(help_text="보급대수", max_length=500)),
                ("ins_dt", models.CharField(help_text="입력일시", max_length=500)),
            ],
            options={
                "db_table": "dbms_ev_car_portal",
            },
        ),
    ]
