# Generated by Django 5.1 on 2024-08-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbms", "0002_evcarportal"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strd_dt", models.CharField(help_text="기준일자", max_length=8)),
                ("market", models.CharField(help_text="마켓", max_length=500)),
                ("stock_day", models.CharField(help_text="주식일자", max_length=500)),
                ("opening_price", models.CharField(help_text="시가", max_length=500)),
                ("high_price", models.CharField(help_text="고가", max_length=500)),
                ("low_price", models.CharField(help_text="저가", max_length=500)),
                ("closing_price", models.CharField(help_text="종가", max_length=500)),
                ("volume", models.CharField(help_text="거래량", max_length=500)),
                ("ins_dt", models.CharField(help_text="입력일시", max_length=500)),
            ],
            options={
                "db_table": "dbms_market_stock",
            },
        ),
    ]
