# Generated by Django 5.1 on 2024-08-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbms", "0003_marketstock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketstock",
            name="stock_day",
            field=models.DateField(help_text="주식일자"),
        ),
    ]
