# Generated by Django 5.1 on 2024-08-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbms", "0004_alter_marketstock_stock_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketstock",
            name="closing_price",
            field=models.FloatField(help_text="종가"),
        ),
        migrations.AlterField(
            model_name="marketstock",
            name="high_price",
            field=models.FloatField(help_text="고가"),
        ),
        migrations.AlterField(
            model_name="marketstock",
            name="low_price",
            field=models.FloatField(help_text="저가"),
        ),
        migrations.AlterField(
            model_name="marketstock",
            name="opening_price",
            field=models.FloatField(help_text="시가"),
        ),
        migrations.AlterField(
            model_name="marketstock",
            name="volume",
            field=models.FloatField(help_text="거래량"),
        ),
    ]
