# Generated by Django 5.1 on 2024-08-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbms", "0005_alter_marketstock_closing_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogKeword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strd_dt", models.CharField(help_text="기준일자", max_length=8)),
                ("keword", models.CharField(help_text="검색어", max_length=500)),
                ("title", models.DateField(help_text="제목")),
                ("link", models.FloatField(help_text="링크")),
                ("ins_dt", models.CharField(help_text="입력일시", max_length=500)),
            ],
            options={
                "db_table": "dbms_blog_keword",
            },
        ),
    ]
