# Generated by Django 5.1 on 2024-08-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbms", "0008_youtubekeword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtubekeword",
            name="main_text",
            field=models.CharField(help_text="본문", max_length=500),
        ),
    ]
