# Generated by Django 5.1 on 2024-08-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbms", "0009_alter_youtubekeword_main_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="KakaoAiImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strd_dt", models.CharField(help_text="기준일자", max_length=8)),
                ("suggest_word", models.CharField(help_text="제시어", max_length=500)),
                ("ins_dt", models.CharField(help_text="입력일시", max_length=500)),
            ],
            options={
                "db_table": "dbms_kakao_ai_image",
            },
        ),
    ]
