# Generated by Django 5.1 on 2024-08-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbms", "0010_kakaoaiimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="KakaoTalk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strd_dt", models.CharField(help_text="기준일자", max_length=8)),
                ("access_token", models.CharField(help_text="접근토큰", max_length=500)),
                ("token_type", models.CharField(help_text="토큰타입", max_length=500)),
                ("refresh_token", models.CharField(help_text="갱신토큰", max_length=500)),
                ("scope", models.CharField(help_text="접근범위", max_length=500)),
                ("upd_dt", models.CharField(help_text="변경일시", max_length=50)),
                ("ins_dt", models.CharField(help_text="입력일시", max_length=50)),
            ],
            options={
                "db_table": "dbms_kakao_talk",
            },
        ),
    ]
