# Generated by Django 5.1 on 2024-08-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbms", "0012_publicapttrade"),
    ]

    operations = [
        migrations.CreateModel(
            name="KmaNeighborhoodWeather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strd_dt", models.CharField(help_text="기준일자", max_length=8)),
                ("strd_tm", models.CharField(help_text="기준시간", max_length=500)),
                ("category", models.CharField(help_text="카테고리", max_length=500)),
                ("nx", models.CharField(help_text="예보지점X좌표", max_length=500)),
                ("ny", models.CharField(help_text="예보지점Y좌표", max_length=500)),
                ("obsr_value", models.CharField(help_text="강수량", max_length=50)),
                ("ins_dt", models.CharField(help_text="입력일시", max_length=50)),
            ],
            options={
                "db_table": "dbms_kma_neighborhood_forecast",
            },
        ),
    ]
