# Generated by Django 5.1 on 2024-11-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbms", "0014_jejuapifloatingpopulation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiDataSum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strd_dt", models.CharField(help_text="기준일자", max_length=8)),
                ("api_nm", models.CharField(help_text="API명", max_length=500)),
                ("data_gb", models.CharField(help_text="API데이터구분", max_length=50)),
                ("data_cnt", models.FloatField(help_text="적재건수")),
                ("memo", models.CharField(help_text="메모", max_length=500)),
                ("ins_dt", models.CharField(help_text="입력일시", max_length=50)),
            ],
            options={
                "db_table": "td_dbms_api_s",
            },
        ),
    ]
